name: Build Flutter iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App (Unsigned)
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      - name: Install CocoaPods (if Podfile exists)
        run: |
          if [ -f ios/Podfile ]; then
            cd ios
            pod install
          else
            echo "No Podfile found. Skipping pod install."
          fi

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build iOS (debug)
        run: flutter build ios --debug

      - name: Upload iOS build artifact (.app)
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app
